{
 "title": "Oracledb2",
 "description": "Oracle dashboard monitors db status, active sessions, user commits, wait times and more.",
 "tags": [ "oracle" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(oracledb_up, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Widgets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "oracledb status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_resource_current_utilization{resource_name=\"sessions\"}",
     "legendFormat": "{{resource_name}}"
    },
    {}
   ]
  },
  {
   "title": "user commits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "execute count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_execute_count{instance=\"$host\"}"
    }
   ]
  },
  { "title": "Exporter Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Diskgroup Free %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "oracledb_asm_diskgroup_free/oracledb_asm_diskgroup_total*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tablespace Free GB",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "oracledb_tablespace_free{type=\"PERMANENT\"}/(1024*1024*1024)",
     "legendFormat": "{{tablespace}}"
    }
   ]
  },
  {
   "title": "last scrape duration seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_exporter_last_scrape_duration_seconds{instance=\"$host\"}\t"
    }
   ]
  },
  {
   "title": "total scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_exporter_scrapes_total{instance=\"$host\"}"
    }
   ]
  },
  { "title": "Table Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "wait time concurrency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "wait time commit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_commit{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "wait time system io",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "wait time user io",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{instance=\"$host\"}\t"
    }
   ]
  },
  {
   "title": "wait time application",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_application{instance=\"$host\"}\t"
    }
   ]
  },
  {
   "title": "wait time network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_network{instance=\"$host\"}\t"
    }
   ]
  }
 ]
}